# Generated by Django 5.2.4 on 2025-07-14 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfile',
            name='user',
        ),
    ]
