# Generated by Django 5.2.4 on 2025-07-15 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_userfile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfile',
            name='report',
            field=models.FileField(blank=True, null=True, upload_to='reports/'),
        ),
    ]
